spring:
  datasource:
        username: root #для сервера
        password: rootpassword #для сервера
        url: jdbc:mysql://212.111.203.173:3306/mydb #внешне подключение до бази
        driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8081